
print("--> affichage d'une liste")
etudiants = ["Alice", "Bob", "Charlie"]
print(etudiants) 
print()
print("--> Ajoute un élément à la fin avec append()")
etudiants.append("Diana")
print(etudiants)
print()
print("--> Insère à une position précise avec insert()")
etudiants.insert(1, "Eve")  
print(etudiants)
print()
print("--> Supprime par valeur avec remove() (enlève la première occurrence)")
etudiants.remove("Bob")
print(etudiants)
print()
print("--> Retire et récupère le dernier élément avec pop()")
dernier = etudiants.pop()
print(dernier)    
print(etudiants)
